### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by adi90x** [mjesuele/hitbtc-api-node#1]
Hello, just trying to run your example, it give me an error : `Unexpected token import` .
Is there any other dependency to add ?

**Comment by mjesuele** [comment]
The example assumes you're using Babel. If you aren't, then
```
import HitBTC from 'hitbtc-api';
```
needs to be
```
cont HitBTC = require('hitbtc-api');
```

See http://stackoverflow.com/questions/39436322/node-js-syntaxerror-unexpected-token-import and https://babeljs.io/.

**Comment by adi90x** [comment]
Thanks a lot for the quick answer !

**Comment by mjesuele** [comment]
No problem, dude! 😎

Let me know if you run into any other problems.
